
export {default as Dashboard} from "./Dashboard";
export {default as Users} from "./Users/index";
export {default as Profile} from "./profile";
export {default as UserDetails} from "./Users/UserDetails";
export {default as Feedback} from "./Feedback";
export {default as ForgetPasswordEA} from "./ForgetPassword-EA";
export {default as ForgetPasswordNP} from "./ForgetPassword-NP";
export {default as ForgetPasswordVC} from "./ForgetPassword-VC";
export {default as FeedbackDetails} from "./Feedback/FeedbackDetails";
export {default as Promo} from "./Promo";
export {default as Driver} from "./Drivers/index";
export {default as BlockedDriver} from "./Drivers/BlockedDrivers";
export {default as DriverDetails} from "./Drivers/DriverDetails";
export {default as BlockDriverProfile} from "./Drivers/BlockDriverProfile";
export {default as PaymentLog} from "./PaymentLogs/index";
export {default as PaymentDetails} from "./PaymentLogs/Paymentdetails";
export {default as Wallet} from "./Wallet";
export {default as VehicleTypes} from "./VehicleTypes/index";
export {default as EditVehicleType} from "./VehicleTypes/EditVehicleType";
export {default as AddNewVehicle} from "./VehicleTypes/AddNewVehicle";
export {default as Commissions} from "./Commissions//index";
export {default as Booking} from "./Booking/index";
export {default as BookingBooked} from "./Booking/BookingBooked";
export {default as Error} from "./Error";
export {default as Login} from "./Login";
export {default as BlockedUserDetails} from "./Users/BlockUserDetails";
// export {default as Dashboard} from "./Dasboard";
// export {default as Dashboard} from "./Dasboard";
// export {default as Dashboard} from "./Dasboard";
// export {default as Dashboard} from "./Dasboard";
// export {default as Dashboard} from "./Dasboard";